name: Rust

on:
  release:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    # install dependencies
    - name: Cache apt
      uses: actions/cache@v4
      id: cache-apt
      with:
        path: ~/dpkg_cache3
        key: ${{ runner.os }}-apt_deps9
    - name: Install packages
      env:
        CACHE_HIT: ${{steps.cache-apt.outputs.cache-hit}}
      run: |
          sudo apt update
          sudo apt install -yq libavutil-dev

    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
